name: CI — develop

on:
  workflow_call:
    inputs:
      dockerfile:
        type: string
        default: "./Dockerfile"
        description: Path to the Dockerfile.
      dockerfile_target:
        type: string
        default: ""
        description: Build target for multi-stage Dockerfiles.

jobs:
  ci:
    uses: minhdqdev-org/github-actions-workflows/.github/workflows/ci.yml@main
    with:
      tag_types: dev_sha
      dockerfile: ${{ inputs.dockerfile }}
      dockerfile_target: ${{ inputs.dockerfile_target }}
